version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: demo-redis
    ports:
      - "6379:6379"
    volumes:
      - ~/docker_volumes/redis_data:/data
    environment:
      - REDIS_PASSWORD=password
    command: redis-server --appendonly yes
